# Generated by Django 4.0.6 on 2022-07-27 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
