# Generated by Django 4.0.6 on 2022-07-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webusers',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='webusers',
            name='phone',
        ),
    ]
