# Generated by Django 4.0.6 on 2022-07-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_webusers_nickname_remove_webusers_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webusers',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='webusers',
            old_name='surname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='webusers',
            old_name='mail',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='webusers',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='webusers',
            old_name='register_date',
            new_name='Register_date',
        ),
    ]
