# Generated by Django 4.0.6 on 2022-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_post',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
