# Generated by Django 4.0.6 on 2022-08-08 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_post',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('economics', 'Economics'), ('science', 'Science')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_posts',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.url_directory),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200, verbose_name='auth.User')),
                ('comment_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_text', models.TextField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.post')),
            ],
        ),
    ]
